services:
  app:
    build: ./app
    container_name: matr3co-python_app
    env_file:
      - ./db/.env           # carrega MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE
    environment:
      FLASK_APP: wsgi.py    # necessário para comandos flask
      FLASK_ENV: development
    networks:
      - matr3co-network
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
    ports:
      - "8000:8000"

  web:
    image: nginx:latest
    container_name: matr3co-nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/app
    networks:
      - matr3co-network
    depends_on:
      - app

  backoffice:
    build:
      context: ./backoffice
    container_name: matr3co-backoffice_app
    env_file:
      - ./db/.env           # reutiliza variáveis de conexão à BD
    environment:
      FLASK_APP: wsgi.py
      FLASK_ENV: production
    networks:
      - matr3co-network
    volumes:
      - ./backoffice:/app
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn -w 4 -b 0.0.0.0:80 wsgi:app
    ports:
      - "81:80"

  db:
    image: mysql:latest
    container_name: matr3co-mysql_db
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - matr3co-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

networks:
  matr3co-network:
    driver: bridge

volumes:
  db_data:
